
import json
import pandas as pd
import plotly.io as pio
from pathlib import Path
from datetime import datetime
from jinja2 import Template

class NotebookExporter:
    """
    Generates a standalone HTML Lab Notebook from analysis results.
    """
    def __init__(self):
        self.template_str = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mustang Analysis Report - {{ date }}</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;800&display=swap" rel="stylesheet">
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <script src="https://3dmol.org/build/3Dmol-min.js"></script>
    <style>
        :root {
            --primary-color: #7B1FA2; /* Deep Purple */
            --secondary-color: #00E5FF; /* Cyan Accent */
            --bg-dark: #0F172A;
            --card-bg: #1E293B;
            --text-color: #E2E8F0;
        }
        body {
            font-family: 'Inter', sans-serif;
            background-color: var(--bg-dark);
            color: var(--text-color);
            padding-bottom: 50px;
        }
        .navbar {
            background: rgba(15, 23, 42, 0.95);
            backdrop-filter: blur(10px);
            border-bottom: 1px solid rgba(255,255,255,0.1);
        }
        .navbar-brand {
            font-weight: 800;
            background: linear-gradient(135deg, #FF0080, #7B1FA2, #00E5FF);
            -webkit-background-clip: text;
            -webkit-text-fill-color: transparent;
            font-size: 1.5rem;
        }
        .section-card {
            background: var(--card-bg);
            border-radius: 12px;
            padding: 25px;
            margin-bottom: 30px;
            border: 1px solid rgba(255,255,255,0.05);
            box-shadow: 0 4px 6px rgba(0,0,0,0.3);
        }
        h2 {
            border-bottom: 2px solid var(--primary-color);
            padding-bottom: 10px;
            margin-bottom: 20px;
            color: #fff;
        }
        .metric-card {
            background: rgba(255,255,255,0.05);
            border-radius: 8px;
            padding: 15px;
            text-align: center;
        }
        .metric-value {
            font-size: 1.8rem;
            font-weight: bold;
            color: var(--secondary-color);
        }
        .metric-label {
            font-size: 0.9rem;
            opacity: 0.8;
        }
        .insight-box {
            background: rgba(0, 229, 255, 0.1);
            border-left: 4px solid var(--secondary-color);
            padding: 15px;
            margin-bottom: 10px;
            border-radius: 4px;
        }
        table {
            color: var(--text-color) !important;
        }
        .table-dark {
            --bs-table-bg: var(--card-bg);
            --bs-table-striped-bg: rgba(255,255,255,0.05);
        }
        .viewer_3d {
            height: 500px;
            width: 100%;
            position: relative;
            background-color: #000;
            border-radius: 8px;
        }
    </style>
</head>
<body>

    <nav class="navbar navbar-expand-lg fixed-top">
        <div class="container">
            <a class="navbar-brand" href="#">🧬 AlignX Lab Notebook</a>
            <span class="text-muted">{{ date }}</span>
        </div>
    </nav>

    <div class="container" style="margin-top: 80px;">
        
        <!-- Header -->
        <div class="text-center mb-5">
            <h1 class="display-4 fw-bold">Analysis Report</h1>
            <p class="lead text-muted">Generated by Mustang Pipeline v2.0</p>
        </div>

        <!-- 1. Key Metrics -->
        <div class="section-card">
            <h2>📊 Alignment Statistics</h2>
            <div class="row">
                <div class="col-md-3">
                    <div class="metric-card">
                        <div class="metric-value">{{ stats.num_structures }}</div>
                        <div class="metric-label">Structures Aligned</div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="metric-card">
                        <div class="metric-value">{{ stats.chain_length }}</div>
                        <div class="metric-label">Alignment Length</div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="metric-card">
                        <div class="metric-value">{{ stats.mean_rmsd }} Å</div>
                        <div class="metric-label">Mean RMSD</div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="metric-card">
                        <div class="metric-value">{{ stats.identity }}%</div>
                        <div class="metric-label">Seq Identity</div>
                    </div>
                </div>
            </div>
        </div>

        <!-- 2. Automated Insights -->
        {% if insights %}
        <div class="section-card">
            <h2>🧠 Smart Insights</h2>
            {% for insight in insights %}
            <div class="insight-box">
                {{ insight | safe }}
            </div>
            {% endfor %}
        </div>
        {% endif %}

        <!-- 3. 3D Structure Viewer -->
        {% if pdb_content %}
        <div class="section-card">
            <h2>🧬 3D Structure Alignment</h2>
            <p class="text-muted">Interactive 3D view of the superimposed structures (Cartoon representation).</p>
            <div id="container-01" class="viewer_3d"></div>
            <script>
                $(function() {
                    let element = $('#container-01');
                    let config = { backgroundColor: 'black' };
                    let viewer = $3Dmol.createViewer( element, config );
                    let pdbData = `{{ pdb_content }}`;
                    viewer.addModel( pdbData, "pdb" );                       /* load data */
                    viewer.setStyle({}, {cartoon: {color: 'spectrum'}});  /* style all atoms */
                    viewer.zoomTo();                                      /* set camera */
                    viewer.render();                                      /* render scene */
                    viewer.zoom(1.2, 1000);                               /* slight zoom out animation */
                });
            </script>
        </div>
        {% endif %}

        <!-- 4. RMSD Heatmap -->
        <div class="section-card">
            <h2>🔥 RMSD Heatmap</h2>
            <p class="text-muted">Pairwise all-vs-all structural comparison.</p>
            <div id="heatmap-plot">
                {{ heatmap_div | safe }}
            </div>
        </div>

        <!-- 5. RMSF Plot -->
        {% if rmsf_div %}
        <div class="section-card">
            <h2>🌊 Residue Flexibility (RMSF)</h2>
            <p class="text-muted">Structural fluctuation per residue position.</p>
            <div id="rmsf-plot">
                {{ rmsf_div | safe }}
            </div>
        </div>
        {% endif %}

        <!-- 6. Ligands -->
        {% if ligand_summary %}
        <div class="section-card">
            <h2>💊 Ligand Summary</h2>
            <p>Ligands identified in the analyzed structures.</p>
            {{ ligand_summary | safe }}
        </div>
        {% endif %}

        <footer class="text-center mt-5 text-muted">
            <p><small>Generated with AlignX v2.0 &bull; {{ date }}</small></p>
        </footer>

    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</body>
</html>
        """

    def generate_notebook(self, results, insights=None):
        """
        Generate HTML notebook from results.
        
        Args:
            results (dict): Pipeline results dictionary.
            insights (list, optional): List of insight strings.
            
        Returns:
            Path: Path to the generated HTML file.
        """
        try:
            # Prepare Data
            stats = results.get('stats', {})
            stats['num_structures'] = len(results.get('rmsd_df', []))
            stats['identity'] = stats.get('seq_identity', 'N/A')
            
            # PDB Content for 3D Viewer
            pdb_content = ""
            if results.get('alignment_pdb') and results['alignment_pdb'].exists():
                with open(results['alignment_pdb'], 'r') as f:
                    pdb_content = f.read()
            
            # 1. Heatmap
            heatmap_fig = results.get('heatmap_fig')
            heatmap_div = pio.to_html(heatmap_fig, full_html=False, include_plotlyjs=False) if heatmap_fig else "<p>No Heatmap Available</p>"
            
            # 2. RMSF (Create fig if only data is present)
            rmsf_div = ""
            if results.get('rmsf_values'):
                import plotly.express as px
                rmsf_data = pd.DataFrame({
                    'Residue Position': range(1, len(results['rmsf_values']) + 1),
                    'RMSF (Å)': results['rmsf_values']
                })
                fig = px.line(rmsf_data, x='Residue Position', y='RMSF (Å)', title='RMSF per Residue', template='plotly_dark')
                rmsf_div = pio.to_html(fig, full_html=False, include_plotlyjs=False)

            # 3. Ligand Table (Convert dict to HTML)
            ligand_html = ""
            if 'ligand_analysis' in results:
                ligand_list = []
                for pdb, ligands in results['ligand_analysis'].items():
                    for l in ligands:
                        ligand_list.append({'Structure': pdb, 'Ligand': l['name'], 'Residue ID': l['id']})
                if ligand_list:
                    df = pd.DataFrame(ligand_list)
                    ligand_html = df.to_html(classes="table table-dark table-striped", index=False)
            
            # 4. Render Template
            template = Template(self.template_str)
            
            # Process insights for HTML (convert markdown bold to HTML bold)
            processed_insights = []
            if insights:
                for i in insights:
                    html_i = i.replace("**", "") # Simple cleanup
                    processed_insights.append(html_i)

            html_content = template.render(
                date=datetime.now().strftime("%Y-%m-%d %H:%M"),
                stats=stats,
                insights=processed_insights,
                heatmap_div=heatmap_div,
                rmsf_div=rmsf_div,
                ligand_summary=ligand_html,
                pdb_content=pdb_content
            )
            
            # Save File
            output_path = results['result_dir'] / "lab_notebook.html"
            with open(output_path, "w", encoding="utf-8") as f:
                f.write(html_content)
                
            return output_path

        except Exception as e:
            print(f"Error generating notebook: {e}")
            return None
